language: csharp
mono: none
dotnet: 2.2.104

install:
  - sudo apt install -qq dotnet-sdk-2.1
  - sudo apt install -qq dotnet-sdk-3.0
  - dotnet tool install coverlet.console --version 1.6.0 --tool-path tools
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
script:
  - dotnet restore
  - dotnet build --no-restore -c Release src/OpenAuth/OpenAuth.csproj
  - dotnet build --no-restore -c Release tests/OpenAuth.UnitTests/OpenAuth.UnitTests.csproj
  - ./tools/coverlet --target dotnet --targetargs "test --no-restore --no-build -c Release tests/OpenAuth.UnitTests/OpenAuth.UnitTests.csproj" tests/OpenAuth.UnitTests/bin/Release/netcoreapp3.0/OpenAuth.UnitTests.dll --format opencover
  - ./tools/csmacnz.Coveralls --opencover -i coverage.opencover.xml
