language: csharp
mono: none
dotnet: 2.1.502

solution: Oath.sln

install:
- dotnet tool install coverlet.console --version 1.6.0 --tool-path tools
- dotnet tool install coveralls.net --version 1.0.0-beta0002 --tool-path tools
- dotnet restore Oath.sln
script:
- dotnet build --no-restore -c Release src/OpenAuth/OpenAuth.csproj
- dotnet build --no-restore -c Release tests/OpenAuth.UnitTests/OpenAuth.UnitTests.csproj
#- dotnet test --no-restore --collect "Code Coverage" -c Release tests/OpenAuth.UnitTests/OpenAuth.UnitTests.csproj
- ./tools/coverlet --target dotnet --targetargs "test --no-restore -c Release tests/OpenAuth.UnitTests/OpenAuth.UnitTests.csproj" tests/OpenAuth.UnitTests/bin/Release/netcoreapp2.1/OpenAuth.UnitTests.dll --format opencover
- ./tools/csmacnz.coveralls --opencover -i coverage.opencover.xml
