language: csharp
mono: none
dotnet: 2.1.502

solution: Oath.sln

install:
- dotnet restore Oath.sln
script:
- dotnet build --no-restore -c Release src/OpenAuth/OpenAuth.csproj
- dotnet test --no-restore --collect "Code Coverage" -c Release tests/OpenAuth.UnitTests/OpenAuth.UnitTests.csproj
